site_name: napari-svg
site_description: An io plugin for writing svg files with napari
site_author: Nicholas Sofroniew

theme: readthedocs

repo_url: https://github.com/sofroniewn/napari-svg

pages:
- Home: index.md
