name = "napari_svg"
publisher = "org.napari"
display_name = "napari SVG"
license = "BSD-3-Clause"
entry_point = "napari_svg"

[[contributions.commands]]
id = "napari_svg.svg_writer"
title = "napari SVG writer"
short_title = "napari SVG"
python_name="napari_svg.hook_implementations:writer"

[[contributions.writers]]
command = "napari_svg.svg_writer"
layer_types = ["image*","labels*","points*","shapes*","vectors*"]
filename_extensions = [".svg"]
save_dialog_title = "napari SVG"